server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: local
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:test}
            client-secret: ${KAKAO_CLIENT_SECRET:test}
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:3000/auth/kakao/callback}
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

openai:
  api-key: ${OPENAI_API_KEY:test}
  api-url: https://api.openai.com/v1

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:diary-images}
    access-key: ${AWS_ACCESS_KEY:test}
    secret-key: ${AWS_SECRET_KEY:test}
    region: ${AWS_REGION:ap-northeast-2}

jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400000 # 24시간

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173
    - http://localhost:5174
    - http://localhost:5175
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

logging:
  level:
    com.diary.backend: DEBUG
    org.springframework.security: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
